#!/bin/bash

SYS_CONF="/etc/photoframe/photoframe.conf"
BOOT_CONF="/boot/photoframe.conf"
CONF="/data/photoframe/photoframe.conf"

test -n "${OS_VERSION}" || source /etc/init.d/base

prepare_conf ${CONF} ${SYS_CONF} ${BOOT_CONF}

test -s ${CONF} || exit 0

test "${OS_NETWORKLESS}" == "true" && exit 0



