#!/bin/bash

SYS_CONF="/etc/photoframe/photoframe.conf"
BOOT_CONF="/boot/photoframe.conf"
CONF="/data/photoframe/photoframe.conf"

PROG=/usr/bin/photoframe.sh

test -x ${PROG} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base

mkdir -p $(dirname $CONF)
prepare_conf ${CONF} ${SYS_CONF} ${BOOT_CONF}

test -s ${CONF} || exit 0
chmod 0600 ${CONF}

start() {
  msg_begin "Syncing photos"
  ${PROG} sync &

  msg_begin "Starting photoframe"
  ${PROG} start > /dev/null &

  test $? == 0 && msg_done || msg_fail
}

stop() {
  msg_begin "Stopping photoframe"
  killall -q $(basename ${PROG})
  test $? == 0 && msg_done || msg_fail
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac

